[package]
name = "chromatic-hue"
version = "0.1.0"
edition = "2021"

[dependencies]
hueclient = "0.4.3"
tokio = { version = "1.29.1", features = ["full"] }
structopt = "0.3"

[dev-dependencies]
async-trait = "0.1.89"
